# simple.gocd.yaml
pipelines:
  demo_dev:
    group: demo
    materials:
      mygit:
        git: https://github.com/torczuk/gocd-sandbox
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: "demo-app"
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - touch some_file.txt
              artifacts:
                - build:
                    source: "*"
                    destination: prata_artifacts