# simple.gocd.yaml
pipelines:
  demo_dev:
    group: demo
    materials:
      mygit:
        git: https://github.com/torczuk/gocd-sandbox
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: "demo-app"
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo 'go cd rules' > file.txt
              artifacts:
                - build:
                    source: "*"
                    destination: prata_artifacts
  demo_dependency:
    group: demo
    materials:
      demo_upstream:
        pipeline: demo_dev
        stage: build