# simple.gocd.yaml
pipelines:
  ingridients:
    group: cooking
    materials:
      mygit:
        git: https://github.com/torczuk/gocd-sandbox
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: "demo-app"
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo 'lets cook prata' > file.txt
              artifacts:
                - build:
                    source: "*"
                    destination: prata_artifacts
  mixing:
    group: cooking
    materials:
      demo_upstream:
        pipeline: ingridients
        stage: build
    stages:
      -  build:
          jobs:
            build:
              elastic_profile_id: "demo-app"
              tasks:
                - fetch:
                    pipeline: ingridients
                    stage: build
                    job: build
                    is_file: yes
                    source: prata_artifacts/file.txt
                    destination: from_upstream/file.txt
  serving:
    group: cooking
      materials:
        mixing:
          pipeline: mixing
          stage: build
        cleaning:
          pipeline: cleaning
          stage: build
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: "demo-app"
              tasks:
                - fetch:
                    pipeline: cleaning
                    stage: build
                    job: build
                    is_file: yes
                    source: cleaning_service/cleaning.txt